### ISSUE TITLE
해결하지 못하는 오류 

### ISSUE THREAD

**Issue by omega0928** [omega0928/react-toy#1]
첨부파일과 같은 에러가 발생하는데 어디를 고쳐야 하는지 모르겠습니다.

문제가 있는 파일: Lotto.jsx
![스크린샷, 2020-01-08 00-31-22](https://user-images.githubusercontent.com/38607469/71906863-47fc2980-31ae-11ea-8bfb-cff0c39a6a6e.png)

**Comment by gogopen85** [comment]
this.timeouts << 선언되지 않은 객체로 보입니다.
